### ISSUE TITLE
Can Myriad be used with .NET 8 or higher?

### ISSUE THREAD

**Issue by NatElkins** [MoiraeSoftware/Myriad#177]
I am trying to bring https://github.com/UnoSD/Pulumi.FSharp.Extensions to .NET 8.  I've changed pretty much every reference from net6.0 to net8.0, but when I try to run the build process I'm getting the following error:

```
Pulumi.FSharp.Myriad -> /Users/nat/Projects/Pulumi.FSharp.Extensions/Pulumi.FSharp.Myriad/bin/Release/net8.0/Pulumi.FSharp.Myriad.dll
  OTHER: System.InvalidOperationException: Dependency resolution failed for component /Users/nat/Projects/Pulumi.FSharp.Extensions/Pulumi.FSharp.Myriad/bin/Release/net6.0/Pulumi.FSharp.Myriad.dll with error code -2147450734. Detailed error: Failed to locate managed application [/Users/nat/Projects/Pulumi.FSharp.Extensions/Pulumi.FSharp.Myriad/bin/Release/net6.0/Pulumi.FSharp.Myriad.dll]
  
     at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
     at McMaster.NETCore.Plugins.Loader.ManagedLoadContext..ctor(String mainAssemblyPath, IReadOnlyDictionary`2 managedAssemblies, IReadOnlyDictionary`2 nativeLibraries, IReadOnlyCollection`1 privateAssemblies, IReadOnlyCollection`1 defaultAssemblies, IReadOnlyCollection`1 additionalProbingPaths, IReadOnlyCollection`1 resourceProbingPaths, AssemblyLoadContext defaultLoadContext, Boolean preferDefaultLoadContext, Boolean lazyLoadReferences, Boolean isCollectible, Boolean loadInMemory, Boolean shadowCopyNativeLibraries)
     at McMaster.NETCore.Plugins.Loader.AssemblyLoadContextBuilder.Build()
     at McMaster.NETCore.Plugins.PluginLoader..ctor(PluginConfig config)
     at McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(String assemblyFile, Action`1 configure)
     at McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(String assemblyFile, Type[] sharedTypes, Action`1 configure)
     at McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(String assemblyFile, Type[] sharedTypes)
     at Myriad.Implementation.findPlugins(String path) in D:\a\myriad\myriad\src\Myriad\Program.fs:line 18
     at Myriad.Main.generators@138.Invoke(String path)
     at Myriad.Main.main(String[] argv) in D:\a\myriad\myriad\src\Myriad\Program.fs:line 137
/Users/nat/.nuget/packages/myriad.sdk/0.8.1/build/Myriad.Sdk.targets(228,9): error MSB3073: The command "dotnet "/Users/nat/.nuget/packages/myriad.sdk/0.8.1/build/../tools/net6.0/any/Myriad.dll" --inputfile "/Users/nat/Projects/Pulumi.FSharp.Extensions/Pulumi.FSharp.AzureNativeV2/Myriad.fs" --outputfile "/Users/nat/Projects/Pulumi.FSharp.Extensions/Pulumi.FSharp.AzureNativeV2/Generated.fs" --configfile "/Users/nat/Projects/Pulumi.FSharp.Extensions/Pulumi.FSharp.AzureNativeV2/myriad.toml" --contextfile "/Users/nat/Projects/Pulumi.FSharp.Extensions/Pulumi.FSharp.AzureNativeV2/obj/myriad.context.toml" --plugin /Users/nat/Projects/Pulumi.FSharp.Extensions/Pulumi.FSharp.Myriad/bin/Release/net6.0/Pulumi.FSharp.Myriad.dll" exited with code 1. [/Users/nat/Projects/Pulumi.FSharp.Extensions/Pulumi.FSharp.AzureNativeV2/Pulumi.FSharp.AzureNativeV2.fsproj]
```

It appears to me that this is failing because Myriad is trying to reference a DLL generated with net6.0 instead of net8.0 (`--plugin /Users/nat/Projects/Pulumi.FSharp.Extensions/Pulumi.FSharp.Myriad/bin/Release/net6.0/Pulumi.FSharp.Myriad.dll"`).  However, I don't believe I'm referencing net8.0 anywhere.  Seems like that `--plugin` param is generated here in Myriad.Sdk.targets:

```xml
<MyriadSdk_Args Include='--plugin %(MyriadSdkGenerator.FullPath)' Condition=" '@(MyriadSdkGenerator)' != '' " />
```

It's a bit tough for me to understand what generates that FullPath value though.

Do you have any pointers?  Thank you!

**Comment by 7sharp9** [comment]
Full path is parameter in the msbuild part

**Comment by 7sharp9** [comment]
plugins are added via a props:

https://github.com/MoiraeSoftware/myriad/blob/3c9818faabf9d508c10c28d5ecd26e66fafb48a1/Myriad%20Configuration%20Changes.md?plain=1#L22

**Comment by 7sharp9** [comment]
Also:  https://github.com/MoiraeSoftware/myriad/pull/173

**Comment by 7sharp9** [comment]
Closed due to #182
